# Update translations when the english master changes

update-po:
	msgmerge -U Danish/strings.po English/strings.po
	msgmerge -U German/strings.po English/strings.po
	msgmerge -U Hebrew/strings.po English/strings.po
	msgmerge -U Norwegian/strings.po English/strings.po
	msgmerge -U Swedish/strings.po English/strings.po
